sudo: required
notifications:
    email: false
language: generic
services:
- docker

arch:
  packages:
  - git
  - go
  script:
  - make
  - make test

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
